version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=${MONGODB_URL}
      - DATABASE_NAME=massist_db
    volumes:
      - ./uploads:/app/uploads
      - ../client:/app/client
    restart: unless-stopped
